# Location of the ports tree
portdir = "/usr/ports"

# Repo order, the port found first is used
order = [
	"punpun",
	"6c37-dropin",
	"core",
	"6c37-git",
	"6c37",
	"opt",
	"xorg",
	"contrib"
]

# Alias ports
alias = [
	[ "core/openssl", "6c37-dropin/libressl" ],
	[ "core/pkg-config", "6c37-dropin/pkgconf" ],
	[ "opt/cairo", "6c37-dropin/cairo-iu" ],
	[ "opt/fontconfig", "6c37-dropin/fontconfig-iu" ],
	[ "opt/freetype", "6c37-dropin/freetype-iu" ]
]

# Characters used for indentation
indentchar = "-  "


[pull]
	[pull.6c37]
	name = "6c37"
	url = "git://github.com/6c37/crux-ports"
	branch = "3.2"

	[pull.6c37-dropin]
	name = "6c37-dropin"
	url = "git://github.com/6c37/crux-ports-dropin"
	branch = "3.2"

	[pull.6c37-git]
	name = "6c37-git"
	url = "git://github.com/6c37/crux-ports-git"
	branch = "3.2"

	[pull.contrib]
	name = "contrib"
	url = "git://github.com/6c37/crux-ports-dropin"
	branch = "3.2"

	[pull.core]
	name = "core"
	url = "git://github.com/6c37/crux-ports-dropin"
	branch = "3.2"

	[pull.opt]
	name = "opt"
	url = "git://github.com/6c37/crux-ports-dropin"
	branch = "3.2"

	[pull.punpun]
	name = "punpun"
	url = "git://github.com/6c37/crux-ports-dropin"
	branch = "3.2"

	[pull.xoxorgxorgrg]
	name = "xorg"
	url = "git://github.com/6c37/crux-ports-dropin"
	branch = "3.2"
